title: BillionVerify
description: Professional Email Verification API with 99.9% Accuracy
url: "https://billionverify.github.io/"
baseurl: ""

# Build settings
markdown: kramdown

# SEO
author: BillionVerify.com

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
