title: EmailVerify.ai
description: Professional Email Verification API with 99.9% Accuracy
url: "https://emailverifysdk.github.io"
baseurl: ""

# Build settings
markdown: kramdown

# SEO
author: EmailVerify.ai

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
